package com.rotiwen.dao;

import com.rotiwen.model.Area;

public interface AreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int insert(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int insertSelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	Area selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int updateByPrimaryKeySelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int updateByPrimaryKey(Area record);
}