package com.rotiwen.dao;

import com.rotiwen.model.Desk;

public interface DeskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table desk
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table desk
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int insert(Desk record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table desk
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int insertSelective(Desk record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table desk
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	Desk selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table desk
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int updateByPrimaryKeySelective(Desk record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table desk
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	int updateByPrimaryKey(Desk record);
}