package com.rotiwen.model;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class Area {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.code
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.name
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.create_time
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.id
	 * @return  the value of area.id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	
	private List<Desk> desks;
	
	public List<Desk> getDesks() {
		return desks;
	}

	public void setDesks(List<Desk> desks) {
		this.desks = desks;
	}

	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.id
	 * @param id  the value for area.id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.code
	 * @return  the value of area.code
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.code
	 * @param code  the value for area.code
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.name
	 * @return  the value of area.name
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.name
	 * @param name  the value for area.name
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.create_time
	 * @return  the value of area.create_time
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.create_time
	 * @param createTime  the value for area.create_time
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@Override
	public String toString() {
		DateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return "id=" + getId() + ";\n" +
			"code=" + getCode() + ";\n" +
			"name=" + getName() + ";\n" +
			"createTime=" + format.format(getCreateTime()) + ";\n";
	}
}