package com.rotiwen.model;

public class Desk {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column desk.id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column desk.code
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column desk.name
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column desk.area_id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	private Area area;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column desk.id
	 * @return  the value of desk.id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column desk.id
	 * @param id  the value for desk.id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column desk.code
	 * @return  the value of desk.code
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column desk.code
	 * @param code  the value for desk.code
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column desk.name
	 * @return  the value of desk.name
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column desk.name
	 * @param name  the value for desk.name
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column desk.area_id
	 * @return  the value of desk.area_id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public Area getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column desk.area_id
	 * @param area  the value for desk.area_id
	 * @mbggenerated  Fri Jun 14 13:20:33 CST 2013
	 */
	public void setArea(Area area) {
		this.area = area;
	}
	
	
	@Override
	public String toString() {
		return "id=" + getId() + ";\n" +
			"code=" + getCode() + ";\n" +
			"name=" + getName() + ";\n" +
			"area:\n" + getArea().toString() + ";\n";
	}
}